# Generated by Django 2.0.7 on 2018-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
